Views wireframe basic
alexansaa/my_blog_app pull request #6
Opened 2023-11-16 22:00 UTC by alexansaa

In this milestone, the following features have been implemented:
- Basic index and show wireframe design implemented on user and post web pages
- Data from the database have been used to render information into the pages
- Basic styles have been used to implement the basic wireframe required
- Different views have been implemented in order to develop the required views designs
- Basic elements like post, user and comment elements have been used through all the project

2023-11-16 22:51 UTC, Lucas-Masaba requested changes
# Hello @alexansaa  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks passing :checkered_flag: 
- Descriptive pull request message :writing_hand: 
- Views look like that in the wireframe :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-16 22:51 UTC, Lucas-Masaba commented on app/views/users/show.html.erb
> +      <% @posts.each_with_index do |post, index| %>
- [ ] Please use the `most_recent_post` method you created in your User model to render the 3 most recent posts as mentioned in the project requirements.

2023-11-16 22:51 UTC, Lucas-Masaba commented on app/views/posts/index.html.erb
> +    <% @posts.each_with_index do |post, index| %>
- [ ] Please use the `most_recent_comment` method you created in your Post model to render the 5 most recent comments as mentioned in the project requirements.

2023-11-16 22:51 UTC, Lucas-Masaba commented on app/views/users/_user.html.erb
- [ ] Please make sure that clicking on a user should take you to the user show page as mentioned in the project requirements.

2023-11-16 22:51 UTC, Lucas-Masaba commented on app/views/users/show.html.erb
> +    <button type="button">See all posts!</button>
- [ ] This button should open a user's post index as displayed in the wireframe and project requirements. Currently, it leads to nowhere

2023-11-17 00:57 UTC, abdulhamiid approved these changes
# :green_circle:  Approved! :partying_face:
Hi @alexansaa 👋, 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Linters checks are passing
- ✔️ Use preprocessed HTML file with embedded Ruby code.

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-17 04:06 UTC, merged